name: Test and Coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests with coverage
        run: flutter test --coverage

      - name: Run integration tests with coverage (if any)
        run: |
          if [ -d integration_test ]; then
            flutter test integration_test --coverage --coverage-path=coverage/lcov_integ.info || true
            # Merge coverage reports if integration tests generated coverage
            if [ -f coverage/lcov_integ.info ]; then
              lcov -a coverage/lcov.info -a coverage/lcov_integ.info -o coverage/lcov_combined.info
              mv coverage/lcov_combined.info coverage/lcov.info
            fi
          fi

      - name: Verify coverage >= 70%
        run: |
          COVERAGE=$(lcov --summary coverage/lcov.info | awk '/lines/{print $4}' | tr -d '%')
          COVERAGE_INT=${COVERAGE%.*}
          echo "Total coverage is ${COVERAGE}%"
          if [ "$COVERAGE_INT" -lt 70 ]; then
            echo "::error::Test coverage ($COVERAGE%) is below the minimum required 70%"
            exit 1
          fi

